#!/bin/bash
ROBOT=myrobotname
ROBOT_ENV=
DISTRO=mydistro
USER=myuser
pcs="
$ROBOT-b1
$ROBOT-t1
$ROBOT-t2
$ROBOT-t3
$ROBOT-s1
$ROBOT-h1"

pcs_cameras="
$ROBOT-t1
$ROBOT-t3
$ROBOT-s1"

if (su $USER -l -c "tmux has-session -t 'bringup' 2> /dev/null"); then
  logger -p user.info "Bringup already running. Exiting"
  echo "Bringup already running. Exiting"
  exit
fi

for i in $pcs; do 
    Alive=False
    Crono=0
    while [[ $Alive=False && $Crono -le 40 ]]
    do
        ping -c 1 -w 3 $i
        if [ $? -ne 0 ] ; then
          Crono=$((Crono+1))
          Timeout=True
          Alive=False
          echo $i not found
        else
          Alive=True
          Timeout=False
          echo $i alive
          break
        fi
        sleep 1
    done
    if [ $Crono -ge 40 ] ; then
      Timeout=True
      echo $i timeout
      break
    else
      Timeout=False
    fi  
done

for i in $pcs_cameras; do 
    Check_cam=False
    while [[ $Check_cam=False ]]
      do
        if ssh $i stat /tmp/check_done \> /dev/null 2\>\&1
          then
            echo "File exists"
            Check_cam=True
            break
          else
            echo "File still does not exist"
        fi
      sleep 1
    done
done

function log() {
  logger -s -p user.$1 ${@:2}
}

#start roscore
/usr/sbin/cob_command  -n roscore -r $ROBOT -c "roscore" -pc $ROBOT-b1 -u $USER

#wait for roscore
until /u/$USER_ROS/git/care-o-bot/devel/env.sh rostopic list; do sleep 1; done

rm -rf /tmp/runningVMS
su mimic -c "ssh $ROBOT-h1 'vboxmanage list runningvms'" > /tmp/runningVMS

if grep -q $ROBOT-win "/tmp/runningVMS"; then
  echo "VM already running"
else
  echo "starting VM..."
  su mimic -c "ssh $ROBOT-h1 'export DISPLAY=:0 && virtualbox --startvm $ROBOT-win --fullscreen'"&
fi

#start bringup
/usr/sbin/cob_command  -n bringup -r $ROBOT -c "roslaunch msh_bringup all.launch env-script:=/u/$USER/git/care-o-bot/devel/env.sh robot_env:=saturn-ingolstadt" -pc $ROBOT-b1 -u $USER

until /u/$USER_ROS/git/care-o-bot/devel/env.sh rosparam get /robot_description > /dev/null ; do sleep 1; done

#start state machine
/usr/sbin/cob_command  -n sm -r $ROBOT -c "roslaunch msh_statemachine machine.launch" -pc $ROBOT-t2 -u $USER
