#!/bin/bash
USER=robot
ROBOT=cob4-5

num=0
blue='\e[1;34m'
black='\e[0;30m'
red='\e[0;31m'
green='\e[1;32m'

source /usr/sbin/tmux_cob
sessions_list=$(list-sessions)

for session_name in $sessions_list
do
  num=$((num+1))
  sessions[$num]=$session_name
done

echo -e "${blue}===========================================${NC}"
echo -e "${blue}===========================================${NC}"
echo -e "${blue}=================cob-stop==================${NC}"
echo -e "${blue}===========================================${NC}"
echo -e "${blue}===========================================${NC}"
echo -e "${black}"Active sessions: "${NC}"

for i in $(seq 1 $num) 
do
  echo "$i: ${sessions[i]}"
done

read -p "Please select a session number or 'all' to kill all the active sessions: " choice

if ! [[ "$choice" =~ ^[1-$num]+$ || "$choice" == "all" ]]
  then
    echo -e "${red}========> $choice not valid , please choose a number session between 1-$num ${NC}"
    exit
fi

if [[ "$choice" == "all" ]]
	then
    echo -e "${green}========> $choice - Stopping all sessions${NC}"
    echo -e "${black}\n ${NC}"
    for i in $(seq 1 $num) 
      do
				su $USER -l -c "ssh $PC 'tmux send -t ${sessions[$i]} C-c'"
				PID=$(ssh $PC "cat /tmp/${sessions[$choice]}.pid" 2>&1)
				while ssh $PC stat /proc/$PID \> /dev/null 2\>\&1 ; do echo "still waiting for ${sessions[$choice]} to stop (PID $PID)" && sleep 1; done
				su $USER -l -c "ssh $PC 'tmux kill-session -t ${sessions[$i]}'"
		done
else
    echo -e "${green}========> $choice - Stopping session ${sessions[$choice]} ${NC}"
    echo -e "${black}\n ${NC}"
		source /usr/sbin/tmux_cob
		PC=$(find-session ${sessions[$choice]})
    su $USER -l -c "ssh $PC 'tmux send -t ${sessions[$choice]} C-c'"
    PID=$(ssh $PC "cat /tmp/${sessions[$choice]}.pid" 2>&1)
    while ssh $PC stat /proc/$PID \> /dev/null 2\>\&1 ; do echo "still waiting for ${sessions[$choice]} to stop (PID $PID)" && sleep 1; done
    su $USER -l -c "ssh $PC 'tmux kill-session -t ${sessions[$choice]}'"
fi
