#!/bin/bash

IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')

client_list=$(nmap --unprivileged $IP-98 --system-dns | grep report | awk '{print $5}') 

function find-session
{
  SESSION_NAME=$1
  for i in $client_list
  do
    sessions_list=$(ssh $i "tmux list-sessions" 2>&1| awk '/:/ { print $1 }')
    sessions_list="${sessions_list//:}"
    if [ "${sessions_list/$SESSION_NAME}" != "$sessions_list" ]; then
      echo $i
      break
    fi
  done
}

function list-sessions
{
  for i in $client_list
  do
    sessions_list=$(ssh $i "tmux list-sessions" 2>&1| awk '/:/ { print $1 }')
    sessions_list="${sessions_list//:}"
    if ! [[ -z "${sessions_list// }" ]]; then
      echo $sessions_list
    fi
  done
}

function list-sessions-v
{
  for i in $client_list
  do
    sessions_list=$(ssh $i "tmux list-sessions" 2>&1| awk '/:/ { print $1 }')
    sessions_list="${sessions_list//:}"
    if ! [[ -z "${sessions_list// }" ]]; then
      echo "$sessions_list ($i)"
    fi
  done
}
